### ISSUE TITLE
Grow dashboard stats font size

### ISSUE THREAD

**Issue by locness3** [BlackrockDigital/startbootstrap-sb-admin#101]
Using a bigger font size for stats' numbers would make them stand out. They are important, and should be big so. Currently they are even smaller than the header title, which is not important at all.

**Comment by davidtmiller** [comment]
This is a design decision that is up to the user.

**Comment by locness3** [comment]
> This is a design decision that is up to the user.

Yeah, but I guess most won't do it @davidtmiller
