### ISSUE TITLE
form-label-group not showing proper when using select

### ISSUE THREAD

**Issue by milan-sahana** [BlackrockDigital/startbootstrap-sb-admin#104]
my code is 

                <div class="form-label-group">
                  	<select name="Type" id="Type" class="form-control" required>
						<option value="Type1">Type1</option>
						<option value="Type2">Type2</option>
						<option value="Type3">Type3</option>
					</select>
              		<label for="Type">Product Type</label>
                </div>

its not showing properly,
but when we use text/password input then its working fine.

**Comment by davidtmiller** [comment]
This is more of a Bootstrap usage issue than an issue with SB Admin
