### ISSUE TITLE
Sidebar hide below screen width 576px

### ISSUE THREAD

**Issue by Bigben83** [BlackrockDigital/startbootstrap-sb-admin#109]
Is there some way that the sidebar can be toggled off when you are below a screen width of 576px

**Comment by Floris999** [comment]
@Bigben83 

You try the media CSS? 

@media (min-width: 576px) {
    .(sidebar-class) or #(sidebar-ID) 
        display: none;
    }

**Comment by davidtmiller** [comment]
cc1a86286617d6dff0df3942ae831d8595158d7e
