### ISSUE TITLE
badge-danger showing on icon to the right

### ISSUE THREAD

**Issue by ShakataGaNai** [BlackrockDigital/startbootstrap-sb-admin#110]
In the demo ( https://startbootstrap.com/previews/sb-admin/ ) , the badge-danger for "9+" shows for the mail icon. However that should be showing up next to the bell: https://github.com/BlackrockDigital/startbootstrap-sb-admin/blob/35a0cb5b69fd7630a2b587bd6b063b75f17f3721/index.html#L52 
The "7" badge is defined under mail and shows on the user portrait. So all of them are offset by one to the right.

![2019-07-22_14-46-05](https://user-images.githubusercontent.com/1415068/61667666-797c4980-ac8f-11e9-8492-1587d36dd152.png)

(Tested on latest Chrome -- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.62 Safari/537.36 -- Also Safari with same behavior)

**Comment by JamesKingdom** [comment]
Same happening here, any updates on this?
Different browsers make no difference, and it used to work fine.

**Comment by davidtmiller** [comment]
cc1a86286617d6dff0df3942ae831d8595158d7e has removed this feature for the time being - I'll revisit this at some point. In the meantime, since this theme uses Font Awesome Free, check out https://fontawesome.com/how-to-use/on-the-web/styling/layering
