### ISSUE TITLE
sidenav toggler default state

### ISSUE THREAD

**Issue by fsykes87** [BlackrockDigital/startbootstrap-sb-admin#111]
I am having trouble getting the side-navbar to load in collapsed mode by default. I have tried adding the class "sidenav-toggled" to the body tag but nothing seems to work.

**Comment by MostlyChrisJ** [comment]
1. Add class `sidebar-toggled` to the body
2. You also need to add `toggled` to the sidebar ul `<ul class="sidebar navbar-nav toggled">`

**Comment by davidtmiller** [comment]
cc1a86286617d6dff0df3942ae831d8595158d7e changes the side nav default state based on browser size
