### ISSUE TITLE
Responsive table doesn't work

### ISSUE THREAD

**Issue by Mark-81** [BlackrockDigital/startbootstrap-sb-admin#114]
Any attempt to create a basic snippet based on Bootstrap only always work. I'm afraid there's something in sb-admin css that interfere, but I don't have the required knowledge to spot.

Basically I have the following layout:

```
<body class="vh-100 d-flex flex-column overflow-hidden">
<nav id="nav_top" class="navbar navbar-expand navbar-dark bg-dark static-top">
    ...
</nav>

<div id="wrapper">
    <ul class="sidebar navbar-nav">
        ...
    </ul>

    <div id="content-wrapper">
        <div class="container-fluid">
            <ol class="breadcrumb">
                ...
            </ol>

            <div id="content" class="row overflow-auto">
                <div class="col-12">
                    <div-class="table-responsive">
                        <table class="table">
                            ...
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
```

With this code, no scroll-bars are shown, so the table is truncated in both x and y.
If I remove the `overflow-hidden` in `<body>` the page grows to show all the table rows.

Instead, I want:

- make a x-responsive table: if the viewport width is too small to show the entire rows a horizontal scroll-bar should appear
- make a y-responsive table that fill all the available viewport height after the top nav-bar and breadcrumb (or any other element above)

Please, would you help me to understand how to do this with your template?

**Comment by davidtmiller** [comment]
cc1a86286617d6dff0df3942ae831d8595158d7e Should make responsive tables work. Otherwise see responsive tables docs on Bootstrap's official docs
