### ISSUE TITLE
Collapse vertical menu

### ISSUE THREAD

**Issue by garak** [BlackrockDigital/startbootstrap-sb-admin#15]
It would be nice to get a collapse functionality, just like the one on Wordpress vertical menu: a link to get the vertical menu shrink (and showing only icons). Best would be with a media query that auto-shrink the vertical menu for a small viewport (keeping the current hamburger menu for very small viewports)

**Comment by kossa** [comment]
Or something like off canvas : https://jasny.github.io/bootstrap/examples/navmenu-reveal/ :+1:

**Comment by garak** [comment]
Well, I don't like off canvas, but I guess it's a personal taste.
Anyway, it' something different from what I'm asking here: my proposal is just an enhancement for the existing vertical menu, not a new menu.

**Comment by zverbatim** [comment]
Very nice suggestion.

**Comment by davidtmiller** [comment]
I'll look into this for a future build, thanks for the suggestion!

**Comment by davidtmiller** [comment]
Added in #39!
