### ISSUE TITLE
Why datatables is not working

### ISSUE THREAD

**Issue by sidaurukfreddy** [BlackrockDigital/startbootstrap-sb-admin#18]
Hello, i have issue why datatables is not working in this template i use codeignter and yes i have been looking for same issue about datatables but it doesn't give me clear please if anyone who face the same problem please comment here i have check many times with standart configuration but give me table with length, here is my code http://pastebin.com/jnq4H2F7

**Comment by kossa** [comment]
Hello,
I'm working with SB-Admin always datatables, and it works fine, without any error, can you make a repo with your example ?

**Comment by sidaurukfreddy** [comment]
Look i have new at github so i'm little bite hard to make repo, repo means show  the link ya ?
did you open a patebin above @kossa 


Thanks

**Comment by kossa** [comment]
sorry for the delay, very simple : http://i.imgur.com/1ER0i7b.png

Or see this video : https://www.youtube.com/watch?v=F3WpBsc0QEw
