### ISSUE TITLE
possible to install via bower?

### ISSUE THREAD

**Issue by ORESoftware** [BlackrockDigital/startbootstrap-sb-admin#19]
on the admin-2 page it says we can install via Bower

what about admin-1?

thx

**Comment by ORESoftware** [comment]
:(

CACSVML-13295:sc-admin-ui-express amills001c$ bower install startbootstrap-sb-admin                                                                                                                                        
bower                        ENOTFOUND Package startbootstrap-sb-admin not found
CACSVML-13295:sc-admin-ui-express amills001c$ bower install startbootstrap-sb-admin-1
bower                        ENOTFOUND Package startbootstrap-sb-admin-1 not found
CACSVML-13295:sc-admin-ui-express amills001c$

**Comment by davidtmiller** [comment]
#25 is referencing this issue
