### ISSUE TITLE
Graph container element not found

### ISSUE THREAD

**Issue by dbassassin** [BlackrockDigital/startbootstrap-sb-admin#20]
I am trying to implement this in a Visual Studio 2015 MVC 5 application.  I receive the following exception at runtime:

Unhandled exception at line 6, column 1334 in http://localhost:53432/js/plugins/morris/morris.min.js

0x800a139e - JavaScript runtime error: Graph container element not found

**Comment by davidtmiller** [comment]
Might have something to do with #24
