### ISSUE TITLE
Can I use this for educational purposes?

### ISSUE THREAD

**Issue by jaijujita** [BlackrockDigital/startbootstrap-sb-admin#21]
Hello! I'm doing a project for my class and I need this for educational purposes. I read the Apache 2.0 license but I don't understand nothing.

(I'm spanish, we don't understand very good the english D:)

Sorry for the inconveniences, and thanks for this!

jaijujita.

**Comment by davidtmiller** [comment]
Yes use it! You can use it for any reason, even commercially!
