### ISSUE TITLE
Flot Charts blank on SB Admin and SB Admin 2 Theme

### ISSUE THREAD

**Issue by Skorium** [BlackrockDigital/startbootstrap-sb-admin#24]
Hi guys,

I'm working on a website based on SB Admin Theme. I notice some charts using Flot Charts are missing. I checked the Demo on StartBootstrap website, and they are also missing on both demo for SB Admin and SB Admin 2 Themes. I tried on Microsoft Edge and Opera Internet browsers, both have the issue. I don't have another Internet browser to run more tests.

I still didn't find a solution to the issue because I'm a new user of bootstrap, I'm working on it at the time but as you know more your theme and how they work than me, I believe it is important to let you know about that.

Cheers

**Comment by davidtmiller** [comment]
Yes I will have to get this fixed. I think the line chart is missing. I will need to review the different chart plugins and update them for the next release of SB Admin 2. Thanks!

**Comment by Skorium** [comment]
No problem, I still didn't figured out (lack of time for this at the moment) but happy to hear you are taking care of that issue.

**Comment by davidtmiller** [comment]
#39 removes usage of Flot charts and Morris charts in favor of Chart.js so this bug is no longer relevant.
