### ISSUE TITLE
bower

### ISSUE THREAD

**Issue by Oldwo1f** [BlackrockDigital/startbootstrap-sb-admin#25]
When i install sb-admin through bower (bower install sb-admin-v2), i install the version 0.1.0

Maybe you can publish the latest version ( 1.4.0).

Thanks by advance, it ll be very helpfull for my workflow.

**Comment by davidtmiller** [comment]
I'll look into this thanks.

**Comment by attenzione** [comment]
maybe together with npm

**Comment by davidtmiller** [comment]
Bower is on the downswing, but an npm package has been created for all templates on Start Bootstrap and they will update automatically on new versions being released.
