### ISSUE TITLE
Uncaught Error: Graph container element not found. 

### ISSUE THREAD

**Issue by djse1993** [BlackrockDigital/startbootstrap-sb-admin#26]
morris.min.js?compile=false:6

**Comment by rready** [comment]
anyone know why using a separate js file with the Morris chart info you get the 'graph container element not found'?

**Comment by davidtmiller** [comment]
I'll check into this, the plugin might be outdated or something.

**Comment by gabrielacosta** [comment]
It is an issue with the way that it is loading the divs and jscript.
Check this 
https://github.com/morrisjs/morris.js/issues/137

**Comment by davidtmiller** [comment]
#39 removed Morris JS and I'm using Chart.js now.

**Comment by yusufsopian** [comment]
I have error js `vendors.bundle.js:78353 Uncaught Error: `

**Comment by yusufsopian** [comment]
`Uncaught Error: Graph container element not found`

**Comment by mohamedchibani** [comment]
http://stackoverflow.com/questions/18176755/morris-js-graph-container-element-not-found
