### ISSUE TITLE
The RTL dashboard messes with text in alert

### ISSUE THREAD

**Issue by svenluijten** [BlackrockDigital/startbootstrap-sb-admin#29]
On the demo page, the glyphicon and exclamation point are reversed. Link: https://blackrockdigital.github.io/startbootstrap-sb-admin/index-rtl.html

![Screenshot](https://cloud.githubusercontent.com/assets/11269635/15628087/89694252-24f8-11e6-95e6-44a1276d5ecd.png)

I'm using the latest version of Chrome (50.0.2661.102 m) without any extensions loaded.

**Comment by davidtmiller** [comment]
Not quite sure what to do about this one...

**Comment by mtaraabi** [comment]
It is make sense when it reversed because is styled for right to left languages. 
here is a version that support RLT https://github.com/poormonfared/sb-admin2 
I added quick fix for some issues in it you will find it in Issues tab

**Comment by ahmadalukah** [comment]
There is no problem this is how RTL languages work

**Comment by davidtmiller** [comment]
The RTL version was removed, I'll look into adding an RTL layout soon, but with the new Bootstrap 4 Beta release #39 this functionality was temporarily removed and will be coming back soon.
