### ISSUE TITLE
dropdown menu icon

### ISSUE THREAD

**Issue by JawnZ** [BlackrockDigital/startbootstrap-sb-admin#31]
Not certain where else to post this, hoping this is the right place.

I'd like the icon to change based on if it's collapsed or not. Is there a way to modify this code to do that? 

`<li>
    <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
    <ul id="demo" class="collapse">
        <li>
            <a href="#">Dropdown Item</a>
        </li>
        <li>
            <a href="#">Dropdown Item</a>
         </li>
    </ul>
</li>`

**Comment by jharris4** [comment]
I made the dropdown menu icon change on expand/collapse by using JavaScript to change the fa-caret-down class to a different font awesome class every time the sub-menu is expanded or collapsed.

If that's not an easy option for you, then I'd suggest trying out the more CSS friendly approach used by the sb-admin-2 example to do changing icons on expand/collapse. The demo is here: https://blackrockdigital.github.io/startbootstrap-sb-admin-2/pages/index.html

You'd have to change this html for each of your dropdowns from this:
`<i class="fa fa-fw fa-caret-down"></i>`

To look more like this:

(example at: https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/blob/master/pages/index.html#L286)
