### ISSUE TITLE
Collapsed side nav can't be scrolled when viewport height is small

### ISSUE THREAD

**Issue by jharris4** [BlackrockDigital/startbootstrap-sb-admin#33]
When viewing the live demo (https://blackrockdigital.github.io/startbootstrap-sb-admin/) I noticed an issue with the side nav when it is collapsed.

On an android phone is landscape mode, or in chrome/firefox/safari on OSX with a small height (300 pixels can be used to reproduce), the collapsed side nav cannot be scrolled to view all of the content.

The scrolling does however work correctly on an iPhone in landscape mode.

**Comment by jharris4** [comment]
Might be the same as this issue actually: https://github.com/twbs/bootstrap/issues/20453

**Comment by os1r1s110** [comment]
Yup pretty much the same problem. Maybe your example will be better to show the problem without putting an "almost impossible" use case. I did this mistake once but hey, newcomer here so I will learn from it.

**Comment by jharris4** [comment]
It's not an "almost impossible" use case. But I think I managed to fix the issue by adding the following rule to my css to override the bootstrap default max-height of 340px:

```
.navbar-fixed-bottom .navbar-collapse, .navbar-fixed-top .navbar-collapse {
    max-height: calc(100vh - 50px) !important;
}
```

In my case I needed to subtract 50px, but I think the live demo would need 100px.

**Comment by os1r1s110** [comment]
Yeah, the problem with my solution (and yours) is that calculation is needed and @mdo seems to not want it in the bootstrap release (he has his reasons that I don't understand but I'm a beginner so I tend to trust his judgement).

**Comment by jharris4** [comment]
I suspect the reason for not including a fix in bootstrap is that it's difficult or impossible to predict what pixel value should be subtracted from the viewport height for all cases.

(Ex: calc(100vh - 50px) vs calc(100vh - 3em) vs calc(100vh - 100px) etc)

**Comment by os1r1s110** [comment]
Effectively, but it could be done via a variable in the _variables.scss file and would fix the problem for everyone this way.... Even for those who don't use the scss files, they could just use a default value (the navbar anyways have a default height if I'm not wrong...)

**Comment by davidtmiller** [comment]
The side navigation was completely overhauled in #39 and this should no longer be an issue!
