### ISSUE TITLE
Change Icon

### ISSUE THREAD

**Issue by dikdableu** [BlackrockDigital/startbootstrap-sb-admin#36]
Hi,

Just a little bit question. I can not find, where i can change the icons of navbar ? 

What mean : 
.fa-subscript:before {
  content: **"\f12c"**;

I'm beginner.

Thank you

**Comment by Ljz7** [comment]
Hello, 

It's a CSS rule. It means that HTML elements that have the `.fa-subscript` class will be prepend by the content of "\f12c" (unicode) that correspond to the subscript icon.

**Comment by davidtmiller** [comment]
The icons being used via CSS are the unicodes that correspond with the fonts. You can find more info at fontawesome.io.
