### ISSUE TITLE
Install with bower

### ISSUE THREAD

**Issue by kukko** [BlackrockDigital/startbootstrap-sb-admin#46]
Can you make this repo installable through bower? I only find the SB Admin 2 with that, but SB Admin 2 user Bootstrap 3 and I want to try out Bootstrap 4 with this template.

Thanks in advance.

**Comment by davidtmiller** [comment]
Yes I will get this registered with Bower at some point soon. Although it's kind of a dying project, I guess Bower support for some of the more popular themes would be good.

**Comment by f3ltron** [comment]
you can close this i think. Bower will not longer being supported.

**Comment by davidtmiller** [comment]
Yep @f3ltron - closing this as Bower is no longer supported.
