### ISSUE TITLE
scroll-y not show

### ISSUE THREAD

**Issue by incubux** [BlackrockDigital/startbootstrap-sb-admin#51]
<ul class="nav navbar-nav  navbar-sidenav" id="exampleAccordion">
I add class ↑↑↑ nav, to be able to use tab-content, invoke tabs and the scroll bar is not shown in the vertical menu when the items are too many.
I could tell that it is the css of the issue that makes conflict, someone can help me, thanks

**Comment by incubux** [comment]
class="navbar-nav  navbar-sidenav" id="exampleAccordion" not work whit tabs, I have to put class = "nav navbar-nav navbar-sidenav", so that it invokes the tabs, but it does not show the scroll-y

**Comment by davidtmiller** [comment]
I'm not quite sure what's going on here, but there is some strange behavior happing at the moment with the overflow-y as it pertains to the positioning of the tooltips when the navbar is collapsed. I will be rebuilding the side nav soon, so I'll close this for now and keep this in mind when rebuilding it.

**Comment by incubux** [comment]
Thank you
