### ISSUE TITLE
Is there a gulp task to build the full set of output files for hosting?

### ISSUE THREAD

**Issue by chmorgan** [BlackrockDigital/startbootstrap-sb-admin#54]
Hello.

I'm looking to see how much space the full set of files would take during a production deployment as a way of looking at the overall footprint of a typical bootstrap 4 project. I can't figure out which files/directory represents the files that are required for hosting even after reviewing the README.md and building and testing the project here locally. Is there a directory where all of those files are located or are they spread out among several in the project?

**Comment by chmorgan** [comment]
And along those same lines, I'd be looking to arrive at the smallest size hosted files as they would be on an embedded target with a limited amount of storage space.

**Comment by davidtmiller** [comment]
The HTML files, the minified CSS, the vendor files that are being used (only the one's you're using), and the minified JS. That should do it. Essentially you can delete the PUG files, the SASS files, and anything else that's not being used and go from there.
