### ISSUE TITLE
Default "sidenav-toggler" state

### ISSUE THREAD

**Issue by arnydo** [BlackrockDigital/startbootstrap-sb-admin#55]
Forgive me for this simple question but how do I set the default state of the sidenav to "Collapsed"?

Thank you.

**Comment by jpkeisala** [comment]
$("#sidenavToggler").click()

**Comment by OLTrustNo1** [comment]
@arnydo Simply add the class "sidenav-toggled" to your body and the sidenav will be collapsed by default.

**Comment by davidtmiller** [comment]
Thanks @jpkeisala and @OLTrustNo1

**Comment by davedodea** [comment]
@davidtmiller 
How is it possible to achieve collapsed sidenav on desktop but also for menu to remain unchanged (if only add "sidenav-toggled" to /body then mobile version drops link wording)on mobile device?
Thanks
