### ISSUE TITLE
Use rem units for navbar offset?

### ISSUE THREAD

**Issue by jharris4** [BlackrockDigital/startbootstrap-sb-admin#57]
Hi, I love that you guys have migrated over to bootstrap 4!

I am a little curious though as to why you're still using pixel (px) units in many places when bootstrap 4 has mostly migrated over to using em/rem units.

In particular, the fixed nav bar using px units for the top padding/margin causes some issues if you "zoom out" in the browser (using "command -" on Mac for example).

The current pixel values result in the content-wrapper getting obscured and the side-nav obscuring the top nav like in the following screen shot:

<img width="932" alt="screen shot 2018-01-09 at 5 42 39 pm" src="https://user-images.githubusercontent.com/7042043/34747056-988639dc-f564-11e7-8e39-3fb953800596.png">

But changing the padding/margin from 56px to 3em seems to fix it. The relevant lines for the changes are:

https://github.com/BlackrockDigital/startbootstrap-sb-admin/blob/master/css/sb-admin.css#L19
https://github.com/BlackrockDigital/startbootstrap-sb-admin/blob/master/css/sb-admin.css#L119

For reference, here are a couple of posts/issues related to the bootstrap switch to rem units:

https://stackoverflow.com/questions/37051697/why-bootstrap-4-choose-rem-and-em-instead-px
https://github.com/twbs/bootstrap/issues/19943

Also, I'd be happy to create a PR for some of these changes if it seems sensible...

**Comment by davidtmiller** [comment]
I will be reviewing this template again and will move to rem's wherever possible. Keeping this open as a reminder. Thanks!

**Comment by stalinsethupathy** [comment]
How to highlight the selected navigation menu in this template

**Comment by davidtmiller** [comment]
New navigation structure in v5.0.0 addresses this.
