### ISSUE TITLE
DataTable plugin not working properly

### ISSUE THREAD

**Issue by adriane34** [BlackrockDigital/startbootstrap-sb-admin#64]
I am using this template for a senior project in college for showing a table on a web page. However, the resulting table is not using DataTable; I have all the necessary files to run the plugin but I am not sure what is going on.
I think some script is missing or not working properly.
![sadsdas](https://user-images.githubusercontent.com/10718566/37013762-6f4458d2-20c1-11e8-8b9e-7c303ba12d6f.JPG)

**Comment by Gevindu** [comment]
change   table id to table id="dataTable"
Refer the table.html file for reference to add a datatable
