### ISSUE TITLE
Missing 4.0.0 git release tag

### ISSUE THREAD

**Issue by cdalexndr** [BlackrockDigital/startbootstrap-sb-admin#65]
NPM latest version is [4.0.0](https://www.npmjs.com/package/startbootstrap-sb-admin), but git latest release is 3.3.7.
Until a new release is made, [webjars ](http://www.webjars.org/) cannot update to new version.

**Comment by jayaddison** [comment]
A `v4.0.0` tag might line up with 5319dac50d21e67d3191a0092989c33e096d4264, I think (based on some analysis to figure out potential breaking changes in an upgrade from v4.0.0)
