### ISSUE TITLE
Collapse sidenav on desktop but keep mobile nav unchanged.

### ISSUE THREAD

**Issue by davedodea** [BlackrockDigital/startbootstrap-sb-admin#71]
@davidtmiller
How is it possible to achieve collapsed sidenav on desktop but also for menu to remain unchanged (if only add "sidenav-toggled" to /body then mobile version drops link wording)on mobile device?
Thanks

**Comment by davidtmiller** [comment]
New navigation structure in v5.0.0 addresses this.
