### ISSUE TITLE
dropdown arrows in navbar wont show

### ISSUE THREAD

**Issue by mikemaddem** [BlackrockDigital/startbootstrap-sb-admin#72]
The arrows show in the card located in the body. But won't show in the navbar.
The dropdown works fine, its just the arrow won't load, other font awesome icons load perfectly fine. I'm using the same FA version included with the documentation

Any help is greatly appreciated! 😄 

![issue](https://user-images.githubusercontent.com/19417674/38462539-d6dc4766-3ab6-11e8-9eb1-31c4efc24793.PNG)
](url)

**Comment by yifanchen** [comment]
@mikemaddem do you know why my changes get restored to the default one every time when I run `gulp dev`?
