### ISSUE TITLE
How to show scrollbar on sidenav?

### ISSUE THREAD

**Issue by cacpmw** [BlackrockDigital/startbootstrap-sb-admin#73]
The sidenav doesn't let me scroll when I have items the exceed the window size. How can I add a scrollbar?

**Comment by yifanchen** [comment]
@cacpmw Do you know why the changes get restored after running 'gulp dev'?

**Comment by tomalessi** [comment]
Add the following to your css/scss:

```
.navbar-sidenav {
  overflow:hidden;
}
```

This will add a hidden scrollbar to the sidenav.  Adding a visible scrollbar throws off the tooltips when the sidenav is collapsed.  I could not solve that part but would prefer the scrollbar to be visible if someone else has a solution.

**Comment by Anduin2017** [comment]
@tomalessi  Thanks. You really solved my problem. Now my website is working correctly. Thank you so much!

**Comment by amatosg** [comment]
@tomalessi thanks, that solved the issue. I've modified the file and it works!

**Comment by davidtmiller** [comment]
New navigation structure in v5.0.0 addresses this.
