### ISSUE TITLE
Bootstrap4 sidebar keeping open on refresh

### ISSUE THREAD

**Issue by alko79** [BlackrockDigital/startbootstrap-sb-admin#86]
hello,
I used on bootstrap3 version of SBadmin a little js code to keep the opened menu  on page refresh or click

but on new version of SBAdmin this is not working anymore.

i tried use the same code for a tabbed menu nav and it works, but when applied to sidebar is not working.

the code just use the id of the <ul> tag to drive the class to show.

here is my snippet:
```
$('.nav a').on('hidden.bs.tab', function (e) { localStorage.setItem(this.id, 'falsetab'); if (!$(this).is(e.target)) { return; } });
$('.nav a').on('shown.bs.tab', function () { localStorage.setItem(this.id, 'truetab'); console.log(this.id); });
$( document ).ready(function() {
for (var i=0; i<localStorage.length ; i++)
{
if (localStorage.getItem(localStorage.key(i)) == 'truetab') { $('#'+localStorage.key(i)).tab('show'); }
}	
});
```
the selector is targeting  $('.nav a') from my tabbed nav and it's working without problem:
```
<ul class="nav justify-content-center btn-secondary" id="myTab" role="tablist">
  <li class="nav-item">
<a class="nav-link active h4 " id="Telecom-tab" data-toggle="tab" href="#Telecom" role="tab" aria-controls="Telecom" aria-selected="true">Telecom</a>
</li>
```

and as I said it worked also on previous version of SBadmin using any data-toggle variable...

but when I use on sidebar <ul> it result empty.

```
<ul class="sidebar navbar-nav " >
<li class="nav-item dropdown" >
<a class="nav-link dropdown-toggle"  id="customersd" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<i class="fa fa-fw fa-user"></i>
<span>CUSTOMER</span>
</a>
```

i tried use the source code directly since I was worried some issue with my php templating framework.
but I get the same problem also on plain html file taken directly from source code.

Is this related to SBadmin sidebar or something from bootstrap4 that I'm missing here?

any guy here for the rescue?

**Comment by mutanttech** [comment]
@alko79, I am facing same issue with SideBar in SBAdmin BootStrap 4 theme. Do you had any luck fixing it, if yes please share solution if feasible. Awaiting your response. Thanks.

**Comment by davidtmiller** [comment]
There is no dynamic portion of this template that will allow for the state of the navbar to remain constant after being toggled since it's just static HTML pages. The best way to do this would use a front end JS framework to handle this.
