### ISSUE TITLE
menu in all html pages

### ISSUE THREAD

**Issue by lucabassplayer89** [BlackrockDigital/startbootstrap-sb-admin#90]
Hi, is there a method to use the same nav menu including it as external source into all html pages?

**Comment by Lukalaga** [comment]
Create a div within a page then add jquery function.


On Oct 18, 2018 3:07 PM, lucabassplayer89 <notifications@github.com> wrote:

Hi, is there a method do use the same nav menu including it as external source into all html pages?

**Comment by lucabassplayer89** [comment]
Could you write a simple example?

**Comment by Lukalaga** [comment]
assume this is the  html page where you want to display the navbar.html

<html>
<body>


<div id="nav-placeholder">

</div>

<script>
$(function(){
  $("#nav-placeholder").load("navbar.html");
});
</script>


and remember to add

<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

within the head tag

________________________________

**Comment by davidtmiller** [comment]
Looks like this was answered.
