### ISSUE TITLE
Select tag default css design prevent showing option tag content in Sb admin 2 theme

### ISSUE THREAD

**Issue by sahanpasindu** [BlackrockDigital/startbootstrap-sb-admin#99]
Hello guys,

I'm working on a project and i'm using Sb admin 2 theme for that. But i have a problem when i using `select` tag with two classes. Which help to make default theme input element with rounded corners instead of default Bootstrap 4 design. So when i put `form-control form-control-user` two css classes for `select` tag, `option` tags values not showing at all, how ever if i remove `form-control-user` css class i can see them with values (`option` tag value) on it and with default Bootstrap 4 design instead of rounded corner design of this theme. That is not what i want. 

Image sample of my problem
[Without option tag values in select tag](https://i.imgur.com/jkmT3Gw.jpg)
[Show click after select tag and option tags styles](https://i.imgur.com/LsXtrk8.png)

I need theme default look and feel for  select tag with options values. And also `option` tag dropdown styles not  good at all. they are odd. How can i archive this problem?

**Comment by davidtmiller** [comment]
This is a customization question and not an issue with the base template itself. I would try Stackoverflow for questions like these.
